module.exports = {
  content: ["../scripts/generate_site.py"],
  safelist: [
    "bg-accent-blue", "bg-primary", "bg-slate-50", "bg-slate-100", "bg-slate-200",
    "bg-slate-300", "bg-slate-800",
    "border-accent-blue",
    "border-blue-200", "border-blue-300",
    "border-emerald-200", "border-emerald-300",
    "border-violet-200", "border-violet-300",
    "border-amber-200", "border-amber-300",
    "border-rose-200", "border-rose-300",
    "border-slate-100", "border-slate-200",
    "text-accent-blue", "text-primary", "text-secondary",
    "text-emerald-600", "text-violet-600", "text-amber-600", "text-rose-500",
    "text-slate-400",
    "hover:border-blue-300", "hover:border-emerald-300", "hover:border-violet-300",
    "hover:border-amber-300", "hover:border-rose-300",
    "hover:bg-slate-100", "hover:bg-slate-200", "hover:text-primary",
    "hover:text-blue-900", "hover:border-accent-blue/30",
    "group-hover:border-blue-300", "group-hover:border-emerald-300",
    "group-hover:border-violet-300", "group-hover:border-amber-300",
    "group-hover:border-rose-300",
    "disabled:opacity-30", "disabled:hover:bg-transparent",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#00288e",
        secondary: "#006591",
        "accent-blue": "#3b82f6",
        surface: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c4c5d5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#444653",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
